// React/src/components/CustomEditor.tsx
import { DropDownBox, Button as DropDownBoxButton } from 'devextreme-react/drop-down-box';
import type { DropDownBoxRef, DropDownBoxTypes } from 'devextreme-react/drop-down-box';
import type { ButtonTypes } from 'devextreme-react/button';
import {
  forwardRef, useCallback, useImperativeHandle, useMemo, useRef, useState, useEffect,
} from 'react';
import {
  TreeList,
  Column,
  Selection,
} from 'devextreme-react/tree-list';
import type { TreeListRef, TreeListTypes } from 'devextreme-react/tree-list';
import { categories } from '../data';
import type { CustomEditorProps, NestedTreeListProps, CustomEditorHandle } from '../types/CustomEditor.types';

function NestedTreeList({
  gridEditorEvent, dropDownArgs, treeListRef, value,
}: NestedTreeListProps): JSX.Element {
  const [selectedRowKeys, setSelectedRowKeys] = useState<number[]>(dropDownArgs?.value != null ? [dropDownArgs.value] : []);

  useEffect(() => {
    setSelectedRowKeys(value != null ? [value] : []);
  }, [value]);

  const onSelectionChanged = useCallback((treeListArgs: TreeListTypes.SelectionChangedEvent) => {
    const selectedId = treeListArgs.currentSelectedRowKeys[0];
    if (!selectedId) return;
    const dropDownBoxInstance = dropDownArgs?.component;
    dropDownBoxInstance?.option('value', selectedId);
    dropDownBoxInstance?.close();
    gridEditorEvent.setValue(selectedId);
    setSelectedRowKeys([selectedId]);
  }, [dropDownArgs, gridEditorEvent]);

  return (
    <TreeList
      height="100%"
      selectedRowKeys={selectedRowKeys}
      ref={treeListRef}
      dataSource={categories}
      keyExpr="id"
      parentIdExpr="parentId"
      onSelectionChanged={onSelectionChanged}
    >
      <Selection mode="single" />
      <Column dataField="name" />
    </TreeList>
  );
}

const CustomEditor = forwardRef<CustomEditorHandle, CustomEditorProps>(
  (({ gridEditorEvent }: CustomEditorProps, ref): JSX.Element => {
    const treeListRef = useRef<TreeListRef>(null);
    const dropDownBoxRef = useRef<DropDownBoxRef>(null);
    const [dropDownBoxValue, setDropDownBoxValue] = useState<number | null>(gridEditorEvent.value);

    const clearDropDownSelection = useCallback(() => {
      setDropDownBoxValue(null);
      dropDownBoxRef.current?.instance().close();
    }, []);

    useImperativeHandle(ref, () => ({
      clearDropDownSelection,
    }), [clearDropDownSelection]);

    const renderTreeList = useCallback(
      (dropDownArgs: DropDownBoxTypes.ContentTemplateData) => <NestedTreeList gridEditorEvent={gridEditorEvent} dropDownArgs={dropDownArgs} treeListRef={treeListRef} value={dropDownBoxValue} />,
      [gridEditorEvent, dropDownBoxValue],
    );

    const dropDownBoxButtonOptions = useMemo<ButtonTypes.Properties>(
      (): ButtonTypes.Properties => ({
        icon: 'remove',
        onClick: (): void => {
          gridEditorEvent.setValue(null);
          clearDropDownSelection();
        },
      }),
      [gridEditorEvent, clearDropDownSelection],
    );

    const dropDownBoxValueChanged = useCallback((e: DropDownBoxTypes.ValueChangedEvent) => {
      setDropDownBoxValue(e.value);
    }, []);

    return (<DropDownBox
      ref={dropDownBoxRef}
      value={dropDownBoxValue}
      onValueChanged={dropDownBoxValueChanged}
      dataSource={categories}
      valueExpr="id"
      displayExpr="name"
      contentRender={renderTreeList}
    >
       <DropDownBoxButton
          location= 'after'
          name= 'customClear'
          options={dropDownBoxButtonOptions}
        />
    </DropDownBox>
    );
  }),
);

CustomEditor.displayName = 'CustomEditor';
export default CustomEditor;

// Vue/src/components/CustomEditor.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import DxDropDownBox, { DxButton as DxDropDownBoxButton } from 'devextreme-vue/drop-down-box';
import type { DxDropDownBoxTypes } from 'devextreme-vue/drop-down-box';
import type { ButtonTypes } from 'devextreme/ui/button';
import DxTreeList, { DxColumn as DxTreeListColumn, DxSelection as DxTreeListSelection } from 'devextreme-vue/tree-list';
import type { DxTreeListTypes } from 'devextreme-vue/tree-list';
import type { DxDataGridTypes } from 'devextreme-vue/data-grid';
import { categories } from '../data';

interface CustomEditorProps {
  gridEditorEvent: DxDataGridTypes.EditorPreparingEvent;
}

const props = defineProps<CustomEditorProps>();

const treeListRef = ref(null);
const dropDownBoxRef = ref(null);
const dropDownBoxValue = ref<number | null>(props.gridEditorEvent.value);
const selectedRowKeys = ref<number[]>(props.gridEditorEvent.value != null ? [props.gridEditorEvent.value] : []);

watch(dropDownBoxValue, (newValue) => {
  selectedRowKeys.value = newValue != null ? [newValue] : [];
});

function onSelectionChanged(e: DxTreeListTypes.SelectionChangedEvent) {
  const selectedId = e.currentSelectedRowKeys[0];
  if (!selectedId) return;
  
  const dropDownBoxInstance = dropDownBoxRef.value?.instance;
  dropDownBoxInstance?.option('value', selectedId);
  dropDownBoxInstance?.close();
  props.gridEditorEvent.setValue(selectedId);
  dropDownBoxValue.value = selectedId;
  selectedRowKeys.value = [selectedId];
}

function dropDownBoxValueChanged(e: DxDropDownBoxTypes.ValueChangedEvent) {
  dropDownBoxValue.value = e.value;
}

function clearDropDownSelection() {
  dropDownBoxValue.value = null;
  dropDownBoxRef.value?.instance?.close();
}

const dropDownBoxButtonOptions: ButtonTypes.Properties = {
  icon: 'remove',
  onClick: () => {
    props.gridEditorEvent.setValue(null);
    clearDropDownSelection();
  },
};

defineExpose({
  clearDropDownSelection,
});
</script>

<template>
  <div>
    <DxDropDownBox
      ref="dropDownBoxRef"
      :value="dropDownBoxValue"
      @valueChanged="dropDownBoxValueChanged"
      :dataSource="categories"
      valueExpr="id"
      displayExpr="name"
    >
      <template #content>
        <DxTreeList
          ref="treeListRef"
          height="100%"
          :selectedRowKeys="selectedRowKeys"
          :dataSource="categories"
          keyExpr="id"
          parentIdExpr="parentId"
          @selectionChanged="onSelectionChanged"
        >
          <DxTreeListSelection mode="single" />
          <DxTreeListColumn dataField="name" />
        </DxTreeList>
      </template>
      <DxDropDownBoxButton
        location="after"
        name="customClear"
        :options="dropDownBoxButtonOptions"
      />
    </DxDropDownBox>
  </div>
</template>
